### ISSUE TITLE
facing issue when import fxdecon

### ISSUE THREAD

**Issue by YuanZi1501040205** [ar4/seispro#1]
![Screenshot from 2021-12-02 17-22-17](https://user-images.githubusercontent.com/50378840/144518693-4a288e44-5f50-4647-b6a8-5fd95ec6e87f.png)

**Comment by YuanZi1501040205** [comment]
I figured it out, the shared.py line 160: `torchaudio.functional.istft` has been deprecated. Just replace it with `torch.istft`
https://stackoverflow.com/questions/64661065/in-torchaudio-0-7-0-where-is-torchaudio-functional-istft

**Comment by ar4** [comment]
Hi Yuan,
Thank you for the report and well done for finding a solution. I will update the code to fix it.
-Alan
